typedb/typedb-protocol

- BUILD
- WORKSPACE
- dependencies/graknlabs/dependencies.bzl
This PR makes `protocol` usable in `@graknlabs_client_python` by exposing `@graknlabs_protocol//:grakn_protocol` target.
- Upgrade `@graknlabs_build_tools` to include graknlabs/build-tools#68
- Add `python_grpc_library` target which generates Python proto/grpc sources and exposes them as `py_library`
> Add Python protocol library

- BUILD
- WORKSPACE
This PR makes `protocol` usable in `@graknlabs_client_nodejs` by exposing `@graknlabs_protocol//:client-nodejs-proto` target.
- Add `node_grpc_compile` target which generates Node proto/grpc sources
> Add NodeJS protocol library

- .circleci/config.yml
- keyspace/BUILD
- session/BUILD
When deploying Maven JARs to Sonatype, the JARs are renamed to be `artifact-id-version.jar`, without the `group-id`. This is done in Sonatype because the JARs are organised into folders where the folder names represent the Group IDs. However, in certain build systems, e.g. Gradle, the JARs are collected under one directory, which means the JAR names are not unique enough to disambiguate itself from each other. We have now renamed the artifact ID of our Maven packages to be prefixed with `grakn-` to solve this problem.
Prefixed artifact IDs of Maven packages with 'grakn-' (fixes https://github.com/graknlabs/grakn/issues/5127, fixes https://github.com/graknlabs/bazel-distribution/issues/112).
> Prefixed artifact IDs of Maven packages with 'grakn-'

- WORKSPACE
- grpc/python/BUILD
Previously, generated Python package contained `keyspace` and `session` packages — which have pretty generic names to be put into user's directory with installed Python packages. This PR moves them under `grakn_protocol` root package.
- Introduced `python_repackage` target which rewires imports in Python generated files
- Replace `imports` in `py_library` so that correct folder is imported
> Repackage Python generated code

- keyspace/Keyspace.proto
Operations with keyspaces need to be authenticated with `username`/`password` in enterprise version. In order to support that, protocol needs to be changed. Additionally, RPC method to create keyspace is now obsolete and needs to be removed.
* Remove `create` RPC method as well as `Create.Req`/`Create.Res`
* Accept `username` and `password` in `Retrieve.Req` and `Delete.Req`
> Authenticate operations in KeyspaceService

- WORKSPACE
Newest changes in `bazel-distribution` (graknlabs/bazel-distribution#181) are backwards-incompatible.
- Uses workspace macros from most recent `bazel-distribution` version
> Adapt to latest @graknlabs_bazel_distribution

- .circleci/config.yml
- grpc/java/BUILD
graknlabs/bazel-distribution#191 changed the way Maven JARs are built. This PR adapts `protocol` to latest changes
* Use `--define` to supply version to Maven deployment rule
* Remove `version_file` from `assemble_maven` arguments
> Adapt to latest changes in bazel-distribution

- session/Answer.proto
With the end goal of streaming deleted concept IDs, we add a backwards-compatible message type `ConceptSingle` that contains a single concept ID. This means deleted concept IDs can now be streamed rather than be returned in one batch as a `ConceptSet`
Related to https://github.com/graknlabs/grakn/issues/4969
* Add a backwards compatible extension to `Answer` message type in `Answer.proto` that can be streamed after a delete
> Add Void Answer Message type

- session/Answer.proto
- session/Session.proto
Explanations can exceed the gRPC message size limits. This change allows retrieving explanations separately from the `ConceptMap` answers themselves, allowing us to break the deep nesting and long messages contained in a single answer. 
The paradigm for retriving an explanation is now as follows:
A `ConceptMap` always contains a `pattern` and a boolean flag `hasExplanation`. If the `ConceptMap` has an explanation, a call can be made using message type `Explanation.Req`, returning a list of `ConceptMap` that correspond to to a single layer of the explanation tree.
Unused `Explanation` messages have been removed from answers other than `ConceptMap`.
* `ConceptMap` contains `conceptMap`, `pattern` and `hasExplanation`
* A new RPC endpoint can be performed by clients using type …
> Retrievable explanations, Restrict explanations to ConceptMaps

- dependencies/graknlabs/dependencies.bzl
We have updated `build-tools`. It fixes the broken build issue caused by the fact that Maven Central artefacts were no longer accessible as the URLs were all HTTP instead of HTTPS.
> Update Build Tools

- .circleci/config.yml
- BUILD
- WORKSPACE
- dependencies/graknlabs/BUILD
- dependencies/graknlabs/dependencies.bzl
- dependencies/maven/BUILD
- dependencies/maven/dependencies.yaml
- dependencies/maven/update.sh
- deployment.properties
- grpc/java/BUILD
- grpc/nodejs/BUILD
- grpc/python/BUILD
- keyspace/BUILD
- keyspace/Keyspace.proto
- kgms/BUILD
- session/Answer.proto
- session/BUILD
- session/Concept.proto
- session/Session.proto
In order for build not to break after graknlabs/build-tools#122, copyright headers need to be updated.
Update copyright headers to match new format
> Update copyright headers to 2020

- session/Concept.proto
- session/Session.proto
Currently, the protocol only returns IDs for every answer. However, it is very rare to only require the ID for a concept e.g. for an attribute you are most likely interested in its value. The goal of this PR is to mitigate the case where hundreds of concept IDs are returned for Attributes from a query, and the client program is going to do a sync RPC to get the value of each.
By taking a selection of example queries run against protocol, we can determine that there are some common requests that are always bounded (if the returned result is a concept, pre-filling it wouldn't lead to recursion). In the case that the returned concept would cause this kind of explosion, or for some reason the results can't be pre-fetched, the `isPrefilled` field notifies a client that this concept wasn't …
> Add prefilling of various response methods

- session/Answer.proto
When the client requests an explanation for a query, we want to also return the rule that is being explained. Therefore, we add the ability to pass a rule inside an explanation.
Required by:
[https://github.com/graknlabs/client-java/pull/81](https://github.com/graknlabs/client-java/pull/81)
[https://github.com/graknlabs/grakn/pull/5657](https://github.com/graknlabs/grakn/pull/5657)
- Add a rule as a `Concept` within an explanation response.
> Add a rule to explanation results

- session/Concept.proto
Previously, we could use `relHas` messages to access the implicit relations used for `has` -- this is no longer an allowed functionality, we only use `has` messages directly now.
* Replace `relHas` with `has` as appropriate
> Remove implicits

- protobuf/answer.proto
- protobuf/concept.proto
- protobuf/session.proto
- protobuf/transaction.proto
To align protocol with the 2.0 Concept API on the server side. A lot of this is simple renaming but some methods have changed slightly. The biggest changes were overridden attributes, roles owned by relations and removal of "key" in favour of parameters for "has".
- Renamed methods to be consistent with 2.0
- Added and removed methods where necessary
> Updating 2.0 concept protocol

- protobuf/concept.proto
To fix Relation.players() always returning an empty collection when called from any external Grakn client (e.g. client-java).
In https://github.com/graknlabs/grakn-2.0/pull/13, we updated the Grakn RPC to take in two different kinds of messages for retrieving roleplayers from a relation; one filtered by roles, and one that isn't.
Then we updated the protocol to represent the new message format, splitting Relation.Players into AllPlayers and PlayersForRoles.
> Split Relation.Players into AllPlayers and PlayersForRoles

- protobuf/concept.proto
To enforce a clear and consistent naming convention for our Concept methods.
Split up Concept methods into 'set' and 'get' where applicable, and renamed 'has' to 'owns' in Type only.
> Refactor Concept methods to use 'set', 'get'; rename Type.'has' to 'owns'

- WORKSPACE
- dependencies/graknlabs/repositories.bzl
- grpc/java/BUILD
Following the implemation of https://github.com/graknlabs/bazel-distribution/pull/248, we can directly depend on `bazel_distribution` for `assemble-maven` and `deploy-maven` rules, and no longer use `graknlabs_dependencies` for this.
* use new implemetatnion of `assemble-maven` with argument for maven overrides
> Assemble maven from bazel_distribution

- protobuf/concept.proto
- protobuf/transaction.proto
- collapse GetPlayers and GetPlayersForRoleTypes into a single message that takes in an array filter, treated as 'do not filter' if it has no elements
- add an optional type filter to Attribute.GetOwners, allowing for retrieval of owners only of a given type
- split SetAbstract into Set and Unset
- feed ConceptMethod either an IID or a Label
> Adapt protocol messages and their namings for 2.0 integration

- protobuf/concept.proto
To add RoleType.getRelation, which currently exists in core but not in clients.
> Add RoleType.GetRelation

- protobuf/concept.proto
- protobuf/transaction.proto
To remove prefilled responses from Thing/Type and slim them down to only the data necessary for a client to construct Things and Types.
We also fix https://github.com/graknlabs/protocol/issues/37 by deleting NULL and replacing it with XXX_NOT_SET when used in the clients and server.
Changed `Thing` to include the following fields:
- **iid** - used to uniquely identify the Thing
- **schema** - either Entity, Relation, or Attribute, used to construct an instance of the Thing
- **valueType** - either Boolean, Long, Double, String, or DateTime, used to construct an Attribute instance
- **value** - the attribute's value, a fundamental property of Attributes
Changed `Type` to include the following fields:
- **label** - used to uniquely identify the Type, unless it is a RoleType
- **schema** - …
> Remove prefilled responses from Thing/Type and slim them down to only the data necessary for a client to construct Things and Types

- .grabl/automation.yml
- protobuf/concept.proto
To align the Type methods in protocol with core.
- Add VALUE_TYPE.OBJECT
- Add support for role overrides
- Make SetRelates response empty
- Allow GetRelatesForRoleLabel to return null
- Pull IsAbstract up from ThingType to Type (but SetAbstract remains in ThingType)
- Add GetOwners to AttributeType
- Add UnsetRelates to RelationType
We also set up `protocol` for CI/CD using grabl.io.
> Align Type methods in protocol with core

- protobuf/concept.proto
Following https://github.com/graknlabs/grakn-2.0/pull/35, we align terminology to not use `schema` but `encoding` for concept root type information.
Rename `schema` to `encoding` to match terminology in grakn 2.0
> Rename schema to encoding to match grakn 2.0

- protobuf/concept.proto
- protobuf/transaction.proto
We split rules from conceptually being a Type in the protocol. They are still viewed as part of the world of "Concepts" in grakn, but as separate elements of the schema, only having a label in common with types.
* Split `Rule` from being part of `Type`
* rearrange `concept.proto` to group the `Concept` definitions at the top, specialised messages below
* compact and clean up numbering ranges of messages - won't affect us (breaking backwards compat anyway)
> Rules are not types and gRPC field compaction

- protobuf/concept.proto
I think you were rushing in implementing `Rule` and `RuleMethod` in `Concept.proto` in PR #64, @flyingsilverfin :) and without enabling CI, you didn't realise that the protocol wasn't building at all.
1) `Rule.SetThen.Res` was not correctly defined: it had an empty `oneof`, which is not a valid syntax.
2) `RuleMethod` was referring to messages that did not exist: `Rule.When` and `Rule.Then` did not exist.
3) `RuleMethod` needed 4 messages each for `req` and `res`: `GetWhen`, `GetThen`, `SetWhen`, and `SetThen` (in that order).
4) `RuleMethod` variable names were not camelCase.
Additionally,
1) `ThingMethod.Req` had a cleanup of message IDs, but some numbers were not properly compacted.
The PR #64 also to reorder the declaration of messages in this file. However, it's partially complete. …
> Fixed implementation of Rule and RuleMethod in Concept.proto

- grpc/java/BUILD
- grpc/nodejs/BUILD
- grpc/python/BUILD
- protobuf/BUILD
- protobuf/answer.proto
- protobuf/query.proto
- protobuf/transaction.proto
To provide protocol messages that fit all the needs of our new Query API 2.0 - specifically Graql Match, Define, Undefine, Insert and Delete, while thinking about forwards compatibility.
Added QueryProto, a new protobuf file that contains two new messages: Query, and Graql.
Query is designed to mimic the structure of Concept; it contains Req, Res, Iter.Req and Iter.Res, which each come in pairs and choose from the various Graql methods available.
The Graql methods are encapsulated in a new message named Graql. Graql contains Match, Define, Undefine, Insert and Delete. These are the possible methods to choose from when constructing a Query.
This is a significant change from our previous structure, where all Graql queries had the same type, and were thus forced to also return the same type …
> Create the new Query API

- protobuf/concept.proto
- protobuf/query.proto
Rules can no longer set a `when` or `then`, and `define` queries no longer return anything.
* Remove `setWhen` and `setThen` messages in `RuleMethod`
* `Define` queries have no return data
> Defines return nothing, Rules have no setters

- protobuf/concept.proto
- protobuf/query.proto
We have observed performance hit caused by sending large amount of grpc calls, to overcome the issue, we allow multiple answers to be batched within one grpc message and we batch them in one grpc call. This way we reduce the number calls we need to make to grpc.
- Make the messages that server may stream back multiple answers into `repeated` field.
> Allow multiple answers batched within one grpc message 

- protobuf/grakn.proto
- protobuf/options.proto
- protobuf/session.proto
1) To ensure Grakn remains usable after a client holding a schema session terminates abruptly: see https://github.com/graknlabs/client-java/issues/193 
2) To improve the UX of waiting for a lock to open a session or transaction: see https://github.com/graknlabs/client-java/issues/194 .
- Add Session.Pulse
- Add new options: IdleTimeoutMillis and AcquireSchemaLockTimeoutMillis
> Add session pulse and configurable timeouts

- protobuf/BUILD
Currently, `build` is broken and fails with the following error:
```
Error: Command failed: /home/grabl/protocol/node_modules/grpc-tools/bin/protoc --plugin=protoc-gen-grpc=/home/grabl/protocol/node_modules/grpc-tools/bin/grpc_node_plugin --plugin=protoc-gen-ts=external/npm/node_modules/grpc_tools_node_protoc_ts/bin/protoc-gen-ts --js_out=import_style=commonjs,binary:./bazel-out/k8-fastbuild/bin/grpc/nodejs/ --grpc_out=grpc_js:./bazel-out/k8-fastbuild/bin/grpc/nodejs/ --ts_out=grpc_js:./bazel-out/k8-fastbuild/bin/grpc/nodejs/ --proto_path=. protobuf/answer.proto protobuf/concept.proto protobuf/database.proto protobuf/grakn.proto protobuf/options.proto protobuf/query.proto protobuf/session.proto protobuf/transaction.proto
protobuf/logic.proto: File not found. …
```
> Fix build job

- .bazelrc
In order to speed up our builds, we should do them remotely on BuildBuddy
Tweak `.bazelrc` settings to build on BuildBuddy with our own Ubuntu 20.04 image
> Build remotely on Ubuntu 20.04

- grpc/nodejs/package.json
- package-lock.json
- package.json
- protobuf/concept.proto
Enforce consistent casing behaviour for enums, and give our npm package the right name.
- All enums are now PascalCased, as in the Protocol Buffers guide.
- The npm package output by `grpc/nodejs:BUILD` is now named `grakn-protocol`.
> Consistent casing for enums + new npm package name

- grpc/python/BUILD
Make grpc/python package correctly importable with pip.
- Do some magic that makes the `py_library` compatible with pip
> Make grpc/python package correctly importable with pip

- protobuf/concept.proto
- protobuf/query.proto
We updated our repeated field names, ensuring they are consistently pluralised in line with the Protocol Buffers style guide.
- Make all repeated fields pluralised
> Make all repeated fields pluralised

- grpc/nodejs/BUILD
Simplify the `genrule` that builds our protocol for Typescript
* Move `//protobuf:proto-raw-buffers` into `srcs` since this is what they are
* Remove symlinking `node_modules` - not needed
* `dirname $(execpath //:WORKSPACE)` always evaluates to `.` (since `WORKSPACE` is a top-level file)
> Simplify NodeJS proto compilation

- .grabl/automation.yml
Grabl recently changed the `automation.yml` syntax to have `image` instead of `machine`
Replace all `machine:` usages with `image:`
> Adapt to new Grabl syntax

- .grabl/automation.yml
Recent version of default GraknLabs Ubuntu image already has Java 11 as default, so specialized version (`-java11`) should no longer be used.
Use `graknlabs-ubuntu-20.04` as image for all jobs
> Switch image back to default Ubuntu 20.04

- BUILD
- WORKSPACE
- dependencies/graknlabs/BUILD
- dependencies/graknlabs/repositories.bzl
- dependencies/maven/BUILD
- dependencies/maven/artifacts.bzl
- dependencies/maven/update.sh
- deployment.bzl
- grpc/java/BUILD
- grpc/nodejs/BUILD
- grpc/nodejs/rules.bzl
- grpc/python/BUILD
- protobuf/BUILD
- protobuf/answer.proto
- protobuf/concept.proto
- protobuf/database.proto
- protobuf/grakn.proto
- protobuf/logic.proto
- protobuf/options.proto
- protobuf/query.proto
- protobuf/session.proto
- protobuf/transaction.proto
License headers are currently out of date (2020) for a while. This PR replaces 2020 with 2021 across all the files.
* Replace `2020` with `2021` in source files
> Bump year in license headers to 2021

- grpc/python/BUILD
Make package naming consistent across multiple language repositories
Rename Python Grakn Protocol package to `grakn-protocol` in order to be consistent with Client NodeJs and Client Java package naming.
> Rename Python protocol package to grakn-protocol

- dependencies/graknlabs/repositories.bzl
- dependencies/maven/artifacts.snapshot
Fix `WARNING: An illegal reflective access operation has occurred` warning caused by an out of date version of protobuf.
- Update protobuf to latest.
> Fix console warnings caused by out of date dependency

- protobuf/options.proto
On executing a Graql query, Grakn automatically streams the first batch of responses back to the client. But, for an `insert` query, they usually don't need those answers. To remedy this, we made `prefetch` a configurable per-query option.
Add prefetch option
> Add prefetch option

- protobuf/cluster/database.proto
- protobuf/options.proto
- protobuf/transaction.proto
We've introduced a new Grakn-Cluster-specific transaction type, "read secondary". It is a read-only transaction that may read not only from primary but also from secondary replicas.
- Adds a new option `allow_secondary_replica`
> Introduce a new transaction type for reading from secondary replicas

- grpc/python/BUILD
Our pip artifact is named `grakn-protocol` but the Python package used to import Python objects from it was inconsistently named `graknprotocol`. So we've renamed it to `grakn_protocol`.
In pip artifact, rename Python package used in imports to grakn_protocol
> Rename Python package in pip artifact to grakn_protocol

- dependencies/graknlabs/repositories.bzl
- grpc/python/BUILD
The Python package names generated for our Cluster proto files were incorrect. We updated our `python_repackage` rules to fix it.
Update our `python_repackage` rules that run against Python package targets so that the Cluster proto files use the correct import paths
> Fix pip package using wrong Python package names

- protobuf/cluster/cluster.proto
- protobuf/cluster/database.proto
- protobuf/cluster/grakn_cluster.proto
Cluster database replicas can now be _preferred secondary replicas_. To encapsulate this we added the flag `preferred_secondary` to `cluster.Database.Replica`.
Additionally, we made the Cluster service methods more transparent by naming them `Cluster.Servers` and `Database.Replicas` (previously `Cluster.Discover` and `Database.Discover`)
- Rename `Cluster.Discover` to `Cluster.Servers`
- Rename `Database.Discover` to `Database.Replicas`
- Add `preferred_secondary` to `cluster.Database.Replica`
> Clarify Cluster service methods and introduce "preferred secondary" replica

- protobuf/options.proto
Add an option that allows users to turn on or off resolution tracing for reasoner. 
- Inference tracing is intended to be set to true only when parallel is set to false.
> Add inference logging option

- .grabl/automation.yml
- protobuf/options.proto
To allow clients to disable parallel execution, we add the `parallel_opt` to `Options.
* add `parallel_opt` to `Options.
> Add parallel option to Options

- protobuf/concept.proto
The `Thing` message now contains a new field, `type`, which holds the concept type. As a result of this change, `value_type` is now redundant (equivalent to `type.value_type`) and `encoding` can be inferred from `type.encoding`, so both fields have been deleted.
Add 'type' field to Thing message; delete `value_type` and `encoding`
> Add 'type' field to Thing

- protobuf/grakn.proto
- protobuf/session.proto
- protobuf/transaction.proto
When sending large amounts of requests from the client to server, it is possible to reach GRPC's maximum throughput of messages per second, on large scale systems. For example, a client with 32 cores, can have 1000 concurrent transactions sending requests to the server. This will easily go beyond what GRPC can handle, and thus becomes the bottleneck in the system. That client will not be sending as many requests it wants per second, and the server may still be able to handle more requests to handle. We have now overcome this problem, by allowing the transaction stream (the predominant GRPC service) to _"batch"_ the transaction requests into one GRPC message to send to the server, within a given time window. In the client-side implementations, we have chosen the time window to be 1 …
> Introduced transaction request batching

- protobuf/cluster/cluster.proto
- protobuf/cluster/database.proto
- protobuf/cluster/grakn_cluster.proto
- protobuf/concept.proto
- protobuf/grakn.proto
- protobuf/logic.proto
- protobuf/query.proto
- protobuf/transaction.proto
The previous definition of Grakn RPC protocol did not differentiate the fact that, for the Transaction Bidirectional Stream, some server responses are complete responses for their associated queries, and others are a partial list of a response which are streamed consecutively to make up a full response incrementally. This makes the protocol not explicitly clear to the developer implementing Grakn clients, without having the internal knowledge of how Grakn server responses are designed. We have now refined the Transaction Bidirectional Stream protocol, to express the server behaviour more explicitly. The Transaction Bidirectional Stream now sends "client" messages and receives back "server" messages. "Server" messages are defined to either be a complete response or a partial response. …
> Architecture Refactor

- .grabl/automation.yml
- common/BUILD
- common/answer.proto
- common/logic.proto
- common/query.proto
We add Explanations, and the explain() query endpoint to the protocol. This enables all clients to retrieve all available explanations for a particular explainable concept map.
* Implement `Explainable` and `Explainables` as part of `Answer` protocol
* Implement `Explanation` as part of `Logic` protocol
* Add `Explain.Req` and `Explain.Res` as part of the explain QueryManager endpoing
> Implement Explanations in RPC

- README.md
Unblock deployment to PyPI
Replace Unicode quotes in `README` with ASCII quotes
> Fix a README to only contain ASCII symbols

- cluster/BUILD
- cluster/cluster_service.proto
- cluster/cluster_user.proto
- grpc/java/BUILD
- grpc/nodejs/BUILD
- grpc/python/BUILD
We have added the user management protocol for TypeDB Cluster. It will allow TypeDB clients to perform user management operations such as adding and deleting a user.
- Add `users_create`, `users_contains`, `users_all`, and `user_delete` endpoints in `TypeDBCluster` service.
> Added user management protocol for TypeDB Cluster

- common/options.proto
To implement transaction timeouts (https://github.com/vaticle/typedb/issues/6487), we need to allow the user to configure the transaction timeout. This PR adds it to the protocol option to adjust the default transaction timeout.
* Add `transaction_timeout_millis` to the options protocol object
> Add transaction timeout to options

- .grabl/automation.yml
- dependencies/vaticle/repositories.bzl
The npm deployment infrastructure now uses token-based authentication instead of username/password authentication.
See https://github.com/vaticle/bazel-distribution/pull/330 for an explanation of why this PR is necessary.
- Update dependencies (to make `deploy_npm` use token authentication) and automation.yml (to pass the token in)
> Use token-based authentication for npm deployment

- .grabl/automation.yml
`deploy-pip-snapshot` was incorrectly being run concurrently with `build` in CI. So we've now marked `build` as a dependency of `deploy-pip-snapshot`.
Add missing CI dependency in deploy-pip-snapshot
> Add missing CI dependency in deploy-pip-snapshot

- dependencies/vaticle/repositories.bzl
The auth token passed to the `deploy_npm` rule, used to deploy the protocol npm package, is now masked in the rule's output logs.
Mask auth token parameter when running deploy_npm
> Mask auth token param when deploying npm package

- .factory/automation.yml
- dependencies/vaticle/repositories.bzl
We've migrated our continuous integration for this repo to Vaticle Factory from Grabl.
We've updated:
- dependencies.
- uses of pyenv that are no longer in line with our approach.
- machine definitions from ubuntu 21.04 to 22.04.
- references to Grabl to Factory.
> Migrate to Factory

- .factory/automation.yml
We've re-instated the use of pyenv in certain Factory job definitions. Removing it in favour of using the system python3 had far-reaching ramifications that proved too costly to immediately address.
We've re-instated our use of pyenv in the `deploy-pip-*` family of jobs.
> Re-instate use of pyenv

- .factory/automation.yml
We've fixed the Python version learned from the successful GitHub deployment of typedb-common a definite working version of Python for this job.
We've changed the used Python version to 3.7.9 from 3.7.12. This fixes a later bug where we attempt to link a library to a not-installed version of Python.
> Use known working python version for GitHub deployment

- .factory/automation.yml
- dependencies/vaticle/repositories.bzl
We fixed a semantic error in `automation.yml` and updated `dependencies`.
- Update prerequisites of `deploy-crate-snapshot` in automation file
- Update `dependencies` to `vaticle` (previously a fork)
> Fix invalid `automation.yml` and update `dependencies`

- dependencies/vaticle/repositories.bzl
We fixed a bug where crate snapshots would fail to deploy, due to passing in an illegal version number.
We've bumped `dependencies` to the latest version to get the fix in:
- https://github.com/vaticle/bazel-distribution/pull/362
It prepends `0.0.0-` to the version number we're deploying, if it looks like a commit SHA - i.e. when it is a snapshot deployment.
Without this fix, the version number we submit is a commit SHA, which, by itself, is not a valid crate version, and is rejected by repo.vaticle.com.
> Fix crate snapshots failing to deploy due to bad version number

- .factory/automation.yml
- dependencies/vaticle/repositories.bzl
We fixed an issue where the Rust protocol would fail to build in Cargo after an IDE sync (by bumping `vaticle_dependencies`)
The fix is in:
- https://github.com/vaticle/dependencies/pull/400
Summary: The `typedb-protocol` crate depends heavily on generated sources (a Rust gRPC + Proto library). The Rust IDE sync tool would generate these sources if run in the `typedb-protocol` repo itself, but not if run from a different repo that depended on Protocol. We fixed that.
> Fix Rust protocol failing to build in Cargo after an IDE sync

- common/concept.proto
`is_root` and `is_abstract` are now snake cased in `Type`.
Protobuf convention is to use snake case. The casing affects the generated code. gRPC Java has been written with fallback logic to handle camelCase, but Python and Node.js do not.
Before this change, we generated the following TypeScript code:
```ts
export class Type extends jspb.Message { 
getIsroot(): boolean;
setIsroot(value: boolean): Type;
getIsabstract(): boolean;
setIsabstract(value: boolean): Type;
```
After the change, these become `getIsRoot`, `setIsAbstract`, etc.
> Snake-case `is_root`, `is_abstract` in `Type`

- cluster/cluster_service.proto
- cluster/cluster_user.proto
We've added two protobuf messages and modified one, enabling us to provide password policy features to TypeDB Cluster. See the PR for further information: https://github.com/vaticle/typedb-cluster/pull/456
We've added:
* `users_password_set`, a message carrying the information for an administrator to overwrite any other user's existing password.
* `users_get`, that returns the user and associated information (currently only the username and the number of days before said user's password expires.)
* The `User` message, which includes all the information returned by `users_get` and `users_all`.
We've modified:
* `users_delete`, moving the method to the user manager.
* `user_password_update`, splitting it into `users_password_set` for administrators and this message that allows user's to …
> Password policy and user management improvement

- common/concept.proto
We replace usages of `boolean` for key arguments with a message type called `Annotation` - this gives us a natural place to extend the set/capabilities of the annotations in the future. The new message type is used to implement the new "unique" annotation.
Introduce `Type.Annotation`, which allows carrying either `Key` or `Unique` annotation. This message type is used through the Concept API protocol specification and replaces all usages of boolean `key` arguments.
> Introduce message types to encode annotations

- common/concept.proto
Implement protocol required to return 'Value' answers in as part of the responses from `match` queries. To support this we generalise some of the message definitions used to transmit attribute values and value types.
* Add the definition of a Value concept to concept.proto
* Add the Value concept to the possible values for a ConceptMap 
* Generalise `AttributeType.ValueType` and `Attribute.Value` to `Concept.ValueType` and `Concept.ConceptValue`. Both `Concept.Attribute` and `Concept.Value` now contain a `Concept.ConceptValue`
> Introduce value query answers

- proto/BUILD
- proto/answer.proto
- proto/query.proto
- proto/version.proto
We implement 'TypeQL Fetch' query protocols, plus refactor the existing protocols around 'Match' queries to use the new 'Get' query terminology. This is a major change to the protocol, so we update the protocol version to `3`.
* Implement 'fetch' query API
* Implement 'fetch' response type: ReadableConceptTree
* We don't expect to expose this type to the user, instead translating it to JSON
* This type primarily lets use re-use message definitions for Concepts
* Refactor existing 'Match' query into 'Get' query terminology
* Update protocol VERSION to 3
> Support TypeQL Fetch queries

- dependencies/vaticle/repositories.bzl
- proto/connection.proto
- proto/version.proto
Added optional driver name and version fields to the Connection.Open request payload. 
Note: despite proto3 being able to handle added fields, due to a library packaging issue, older versions of TypeDB cannot handle new fields. This means that this change breaks backwards compatibility.
> Add driver fields to the connection open request

- .factory/automation.yml
- dependencies/vaticle/repositories.bzl
- grpc/nodejs/BUILD
- grpc/rust/BUILD
Updates artifact deployment & consumption rules to use cloudsmith instead of the self-hosted sonatype repository.
* Bump `vaticle_dependencies` & update deployment targets
> Migrate artifact hosting to cloudsmith

- .factory/automation.yml
We add a sync-dependencies job to be run in CI after successful snapshot and release deployments. The job sends a request to vaticle-bot to update all downstream dependencies.
Note: this PR does _not_ update the `dependencies` repo dependency. It will be updated automatically by the bot during its first pass.
> Sync dependencies in CI

- .bazelrc
- WORKSPACE
- dependencies/maven/artifacts.snapshot
- grpc/nodejs/BUILD
We update dependencies to fix `typedb-protocol` build.
We use the updated rules fixed in [dependencies](https://github.com/vaticle/dependencies/pull/547) and also update the code based on the new requirements of the updates `ts` rules.
We also update `maven` dependencies based on other `sync-dependencies` commits to fix the build.
> Fix type script rules after updated dependencies

- proto/query.proto
In 3.0, we no longer use parsers on our user-facing clients, and we no longer can differentiate the types of queries we are executing on the server. However, it can be sometimes useful (e.g. for extra logging/messaging) to have at least some information about the nature of the queries. 
For these purposes, we add the executed query's type to `ConceptRowStream`. 
For now, it's just general `Read/Write/Schema` (like transaction types), which is enough for our existing tasks.
> Add Query::Type to ConceptRowStream

- proto/answer.proto
- proto/concept.proto
- proto/query.proto
We implement Fetch queries, which return concept Document streams.
> Implement Fetch protocol using Document return type

- proto/typedb-service.proto
- proto/user.proto
Declare user management messages and services, which lets the caller make user creation, update, deletion, and retrieval call through gRPC.
Declare the associated gRPC services and Protobuf messages for user creation, update, deletion, and retrieval.
> User management protocol

- proto/concept.proto
Renames the TypeQL `long` datatype to `integer`
> Rename long to integer

- grpc/java/BUILD
- grpc/nodejs/BUILD
- grpc/rust/BUILD
- grpc/rust/build.rs
- proto/BUILD
- proto/authentication.proto
- proto/connection.proto
- proto/query.proto
- proto/typedb-service.proto
- proto/version.proto
A new mechanism of authentication tokens has been introduced to replace the old way of sending usernames and passwords through the network with every request.
Instead, all user credentials (currently, it's usernames and passwords) are sent only:
* as a part of `connection_open` request for authentication and authorization, with a temporary token returned;
* as a part of `sign_in` request for sign ins within an established connection (to change the user or to get a new authentication token).
Then, all further requests are expected to be authenticated only by temporary, less sensitive tokens. 
The approach is extensible to other credential types that can be introduced in the future.
> Add sign-in request for authentication token retrieval

- .factory/automation.yml
- dependencies/typedb/repositories.bzl
- proto/BUILD
Support build on Apple Clang 17+ by updating dependencies (details: https://github.com/typedb/typedb-dependencies/pull/577). 
Fix bazel build by adding an implicit dependency to the build configuration.
Reintroduce CI correctness validation jobs.
> Fix build errors and update dependencies

- proto/BUILD
- proto/connection.proto
- proto/database.proto
- proto/error.proto
- proto/server.proto
- proto/typedb-service.proto
Introduce cluster support for TypeDB 3.x, featuring server replicas and the new version message.
Remove database replicas. Instead, add server replicas (by extending the usual `Server` message) with a similar set of fields.
Instead of adding a `is_primary` flag, introduce an extensible enum `ReplicaType` for more granular split between primary and supporting nodes.  
To reduce the network overhead, this new information is provided in the initial server's connection response.
> Add cluster support

- proto/BUILD
- proto/raft-peering-service.proto
- proto/raft-peering.proto
- proto/server.proto
Add server_status message to the raft peering service and rename the old raft peering messages to adjust to the existing naming conventions.
> Add server_status message to the raft peering service
