.circleci/config.yml, BUILD, WORKSPACE, dependencies/graknlabs/BUILD, dependencies/graknlabs/dependencies.bzl, dependencies/maven/BUILD, dependencies/maven/dependencies.yaml, dependencies/maven/update.sh, deployment.properties, grpc/java/BUILD, grpc/nodejs/BUILD, grpc/python/BUILD, keyspace/BUILD, keyspace/Keyspace.proto, session/Answer.proto, session/BUILD, session/Concept.proto, session/Session.proto
Bump 2018 in license headers to 2019
=> Update License to 2019

.circleci/config.yml
Fix sync-dependencies-release job and working directories in various jobs
=> Fix sync-dependencies-release job and working directories in various jobs

session/Session.proto
To implement the protocol change required in #25 
- Added an `all` boolean to `Transaction.Iter.Req`
=> Added an `all` option to Transaction.Iter.Req

session/Concept.proto, session/Session.proto
=> Revert "Add prefilling of various response methods"

WORKSPACE
Recent upgrade to Python 3 broke our CI.
- Use updated imports from `@rules_python`
=> Fix CI issues related to Python upgrade

.circleci/config.yml, dependencies/graknlabs/dependencies.bzl
Use Ubuntu 16 CI image and update build tools
=> Use Ubuntu 16 CI image and update build tools

protobuf/concept.proto
=> Rename BASE_TYPE to SCHEMA

protobuf/concept.proto
To allow clients to do RPC calls to determine if types are root types
## What are the changes implemented in this PR?
Added Type.IsRoot
=> Add Type.IsRoot

WORKSPACE
To clean up unused dependencies from the workspace file.
=> Clean bazel WORKSPACE dependencies

protobuf/transaction.proto
=> Add GetRule

.grabl/automation.yml, grpc/java/BUILD, grpc/nodejs/BUILD, grpc/python/BUILD, protobuf/BUILD, protobuf/database.proto, protobuf/grakn.proto, protobuf/session.proto, protobuf/transaction.proto
To ensure that services that are inseparable from each other are in fact not separated.
SessionService is useless without a Database from the DatabaseService; TransactionService is useless without a Session from the SessionService. On the server side, the three have a network of dependencies between each other.
Dissolve the 3 services back into one service named Grakn.
=> Dissolve the 3 services back into one service named Grakn

.grabl/automation.yml
Repair automation.yml
Repair broken indentation in automation.yml
=> Fix automation

.grabl/automation.yml, WORKSPACE, dependencies/graknlabs/repositories.bzl, dependencies/maven/artifacts.snapshot
In order for us to know whether our dependencies are up-to-date, we integrate `dependency-analysis` job into `quality` workflow
* Specify dependencies on other repos in `.grabl/automation.yml`
* Add `dependency-analysis` to `quality` workflow
* Upgrade `graknlabs_dependencies`
=> Integrate dependency-analysis job

grpc/nodejs/package.json, package.json
The name of the npm package produced for client-nodejs is inconsistent with the other packages. This PR changes it to be consistent.
Renames package in package.json.
=> Change package name for npm

.bazelrc, .gitignore, .grabl/automation.yml, dependencies/graknlabs/repositories.bzl, grpc/python/requirements.txt
Currently, checkstyle tests are broken due to old year in the header (2020)
Update license headers
=> Fix checkstyle tests

protobuf/logic.proto
We added a new LogicManager method, named GetRules, that fetches every rule in a database.
Add GetRules to LogicManager
=> Add GetRules to LogicManager

cluster/BUILD, cluster/cluster_client.proto, cluster/cluster_service.proto, cluster/cluster_user.proto, cluster/cluster_user_token.proto, grpc/java/BUILD, grpc/nodejs/BUILD, grpc/python/BUILD
We have introduced a new protocol for performing authentication token renewal in TypeDB Cluster.
1. Added a new service `user_token_renew`
2. Added `Renew` request and response object
=> Token renewal protocol for TypeDB Cluster

RELEASE_TEMPLATE.md
Releases now include information about our PyPI and NPM packages.
Given that we deploy not just to Maven, but also to PyPI and NPM, it seems prudent to document all 3 (or none of them!)
=> Add PyPI and NPM packages to release template

dependencies/vaticle/repositories.bzl
We fixed a bug where the package deployment to npm would fail with an authentication error.
Update dependencies
=> Fix npm deployment failing with auth errors

.grabl/automation.yml, BUILD, LICENSE, cluster/BUILD, common/BUILD, core/BUILD, dependencies/maven/BUILD, dependencies/vaticle/BUILD, dependencies/vaticle/repositories.bzl, grpc/java/BUILD, grpc/nodejs/BUILD, grpc/python/BUILD
We introduce a test that ensures that the license text is correct.
* Bring all the `checkstyle_test()` invocations in line with the updated definition in dependencies;
* Use checkstyle to confirm that the license text is correct.
=> Extend checkstyle license test and update licenses

dependencies/vaticle/repositories.bzl
Bump Vaticle dependencies.
* Update `vaticle/dependencies` dependency's commit SHA to the latest one
=> Bump Vaticle dependencies

dependencies/typedb/repositories.bzl
=> Update dependencies for release 3.2.0-rc0
